
FROM debian:bullseye
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/sshd"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV PASSWD_DIR     /opt/sshd/etc
ENV SSH_SERVER_DIR /opt/sshd/etc/ssh

INCLUDE ../_includes/05_localenv.docker
INCLUDE ../_includes/10_setup.docker


# MAIN
#-----
RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
     rsync  \
     ssh    \
 && apt-get clean'

RUN  mkdir -p /var/run/sshd
COPY docker /docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 22

CMD exec /docker/run
