
FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/postgresql"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV UID_POSTGRES 202
ENV GID_POSTGRES 202

INCLUDE ../_includes/05_localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
RUN groupadd -g $GID_POSTGRES postgres
RUN useradd --system                         \
    --home /opt/postgresql                   \
    --shell /bin/sh                          \
    -M                                       \
    --uid $UID_POSTGRES                      \
    --gid $GID_POSTGRES                      \
    --comment "PostgreSQL administrator,,,"  \
    postgres

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql

RUN install -d -m 2775 -o postgres -g postgres /var/run/postgresql

RUN rm -rf /var/lib/postgresql

RUN PG_ETC=/etc/postgresql/*; mv $PG_ETC /etc/postgresql/tmpl; ln -s /opt/postgresql/conf $PG_ETC

RUN sed -i "/^data_directory[ =]/cdata_directory = '/opt/postgresql/data'"        /etc/postgresql/tmpl/main/postgresql.conf
RUN sed -i "/^ssl[ =]/cssl = false"                                               /etc/postgresql/tmpl/main/postgresql.conf
RUN perl -pi -e "s#/etc/ssl#/opt/postgresql/conf/ssl#"                            /etc/postgresql/tmpl/main/postgresql.conf

COPY docker /docker

# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 5432

CMD exec /docker/run
