
Dockerfiles
===========

These are just a bunch of `Dockerfile` which I use at work and on my
machines. I run a `Dcokerfile.in` through a simple perl script so that I
can include common components (apt proxy, standard packages, common
cleanup).

You alomost certainly want to fork this repository or just copy/paste bits
into your own dockerfiles. I am making no efforts at sane upgrades, I am
inconsistent with naming and versioning (sometimes just upgrading
containers and sometimes creating new containers with -debXX appended).

The `bin` directory includes some scripts to link include files from
another folder (for "vendorization") and scripts to automatically manage
updates and cleanup of old versions. The intent is to periodically (and
automatically) call `docker-build` to ensure security updates are regularly
applied to containers.


== Volumes

These dockerfiles are set up to use a single volume for both configuration
and perminant storage. Contrary to recommended practices, I typically mount
plain directory volumes rather than use storage containers, so that is what
all the samples use. Feel free to use storage containers if you like.


== Project Structure

Typical Directory Structure:

    Dockerfile.in
    Makefile
    README.md
    docker/
    ├── init
    ├── reload
    ├── run
    └── stop

Most `Dockerfile.in` end with `CMD exec /docker/run` and the docker
commands `reload` and `stop` are perform actions appropriate for the
corresponding systemd commands.

I try to make `/docker/run` perform initialization as needed, including
initialization of reasonable config files when absent and creation of any
required directories. The intent is to simply run the container on an empty
directory for initial setup and just run the container on a configured
directory for normal use. Occasionally, something will need a bit more
setup and will have a `/docker/init` or `/docker/upgrade` script as well. Each
directory's README will explain the required setup procedure.
