#!/bin/bash
VERSION='0.1.0';# Created: 2015-04-22
# set -x           # enable echoing of commands
set -o nounset     # Die if any variable is unset
set -o errexit     # set +e; COMMAND; set -e to temporarily disable
set -o pipefail    # die even if failure in a pipe
# set -o noclobber   # redirects may not clobber files

DIRECTORY=${1:?Must provide directory}
NAME=${2:?Must provide container name}
SERVICE=${3:?Must provide service name}

cd "$DIRECTORY"
make upgrade NAME="$NAME" && systemctl restart "$SERVICE"
