
FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/www"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker
INCLUDE ../_includes/05_localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
RUN apt-get update && apt-get install -y --no-install-recommends \
    starman \
 && apt-get clean

COPY docker /docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 5000

CMD exec docker/run
