
FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>

# jessie moved to archive.debian.org, containers not updated
RUN sed -i '/jessie-updates/d' /etc/apt/sources.list ; \
    sed -i 's/deb.debian.org/archive.debian.org/' /etc/apt/sources.list


# CONFIGURATION
#--------------
VOLUME ["/www"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker
INCLUDE ../_includes/05_localenv.docker
INCLUDE? localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
    starman \
 && apt-get clean'

COPY docker /docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 5000

CMD exec docker/run
