
## This is a release builder, launch it, then once it is finished
## export/import the result to get a fixed object.

FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/puppet"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV UID_PUPPET 200
ENV GID_PUPPET 200

INCLUDE ../_includes/05_localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
RUN addgroup --gid $GID_PUPPET puppet
RUN adduser --system        \
    --home /var/lib/puppet  \
    --shell /bin/false      \
    --no-create-home        \
    --uid $UID_PUPPET       \
    --gid $GID_PUPPET       \
    --disabled-password     \
    --disabled-login        \
    puppet

RUN apt-get update && apt-get install -y --no-install-recommends \
    puppet-module-puppetlabs-inifile \
    puppet-module-puppetlabs-stdlib  \
    puppetmaster-passenger           \
    ruby-rgen

RUN rm -f /etc/puppet/puppet.conf                        && ln -s /opt/puppet/etc/puppet.conf                           /etc/puppet/puppet.conf
RUN rm -f /etc/apache2/sites-enabled/puppetmaster.conf   && ln -s /opt/puppet/extra/apache2/puppetmaster-passenger.conf /etc/apache2/sites-enabled/puppetmaster.conf

# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 8140

ENV APACHE_RUN_USER      www-data
ENV APACHE_RUN_GROUP     www-data
ENV APACHE_LOG_DIR       /var/log/apache2
ENV APACHE_PID_FILE      /var/run/apache2.pid
ENV APACHE_RUN_DIR       /var/run/apache2
ENV APACHE_LOCK_DIR      /var/lock/apache2
ENV APACHE_SERVERADMIN   dean@serenevy.net
ENV APACHE_SERVERNAME    puppet
ENV APACHE_SERVERALIAS   puppet.machinemotion.com
ENV APACHE_DOCUMENTROOT  /var/www

CMD [ "/usr/sbin/apache2", "-DFOREGROUND" ]
