
FROM debian:buster
MAINTAINER Dean Serenevy <dean@serenevy.net>

# CONFIGURATION
#--------------
VOLUME ["/www"]

ARG LSMB_VERSION="1.7.17"
ARG LSMB_DL_DIR="Releases"

ENV MAILHUB  host-auto
ENV UID_USER 1000
ENV GID_USER 1000

# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker
INCLUDE ../_includes/05_localenv.docker
INCLUDE? localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
COPY docker/keyring.kbx /tmp/keyring.kbx
RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
 ca-certificates \
 fonts-liberation \
 libauthen-sasl-perl \
 libcgi-emulate-psgi-perl \
 libconfig-inifiles-perl \
 libcookie-baker-perl \
 libcpanel-json-xs-perl \
 libdatetime-format-strptime-perl \
 libdatetime-perl \
 libdbd-pg-perl \
 libdbi-perl \
 libemail-sender-perl \
 libemail-stuffer-perl \
 libexcel-writer-xlsx-perl \
 libfile-find-rule-perl \
 libhtml-escape-perl \
 libhtml-parser-perl \
 libhttp-headers-fast-perl \
 libhttp-message-perl \
 libio-stringy-perl \
 libjson-maybexs-perl \
 libjson-pp-perl \
 liblatex-driver-perl \
 liblist-moreutils-perl \
 liblocale-maketext-lexicon-perl \
 liblog-log4perl-perl \
 libmailtools-perl \
 libmath-bigint-gmp-perl \
 libmime-lite-perl \
 libmime-types-perl \
 libmodule-runtime-perl \
 libmoo-perl \
 libmoose-perl \
 libmoosex-nonmoose-perl \
 libmoox-types-mooselike-perl \
 libnamespace-autoclean-perl \
 libnumber-format-perl \
 libopenoffice-oodoc-perl \
 libossp-uuid-perl \
 libpath-class-perl \
 libpgobject-perl \
 libpgobject-simple-perl \
 libpgobject-simple-role-perl \
 libpgobject-type-bigfloat-perl \
 libpgobject-type-bytestring-perl \
 libpgobject-type-datetime-perl \
 libpgobject-util-dbadmin-perl \
 libpgobject-util-dbmethod-perl \
 libplack-builder-conditionals-perl \
 libplack-middleware-reverseproxy-perl \
 libplack-perl \
 libplack-request-withencoding-perl \
 libscope-guard-perl \
 libsession-storage-secure-perl \
 libspreadsheet-writeexcel-perl \
 libstring-random-perl \
 libtemplate-perl \
 libtemplate-plugin-latex-perl \
 libtex-encode-perl \
 libtext-csv-perl \
 libtext-markdown-perl \
 libtry-tiny-perl \
 libversion-compare-perl \
 libwww-perl \
 libx12-parser-perl \
 libxml-libxml-perl \
 libxml-sax-expat-perl \
 libxml-simple-perl \
 libxml-twig-perl \
 lmodern \
 msmtp \
 postgresql-client \
 starman \
 texlive-latex-recommended \
 texlive-pstricks \
 texlive-xetex \
 wget \
 gpgv git cpanminus make gcc libperl-dev \
 && rm -f /usr/sbin/sendmail \
 && ln -s /usr/bin/msmtp /usr/sbin/sendmail \
 && wget --quiet -O /tmp/ledgersmb-$LSMB_VERSION.tar.gz     "https://download.ledgersmb.org/f/$LSMB_DL_DIR/$LSMB_VERSION/ledgersmb-$LSMB_VERSION.tar.gz" \
 && wget --quiet -O /tmp/ledgersmb-$LSMB_VERSION.tar.gz.asc "https://download.ledgersmb.org/f/$LSMB_DL_DIR/$LSMB_VERSION/ledgersmb-$LSMB_VERSION.tar.gz.asc" \
 && gpgv --keyring /tmp/keyring.kbx /tmp/ledgersmb-$LSMB_VERSION.tar.gz.asc /tmp/ledgersmb-$LSMB_VERSION.tar.gz \
 && tar -xf /tmp/ledgersmb-$LSMB_VERSION.tar.gz -C /srv \
 && rm -f /tmp/ledgersmb-$LSMB_VERSION.tar.gz \
 && cpanm --notest \
    --with-feature=edi \
    --with-feature=latex-pdf-ps \
    --with-feature=openoffice \
    --with-feature=xls \
    --installdeps /srv/ledgersmb/ \
 && mv /srv/ledgersmb/templates /srv/ledgersmb/templates.orig \
 && ln -s /www/templates /srv/ledgersmb/templates \
 && apt-get purge -q -y gpgv git cpanminus make gcc libperl-dev wget \
 && apt-get autoremove -q -y \
 && apt-get clean -q \
 && rm -rf ~/.cpanm/ /var/lib/apt/lists/* /usr/share/doc/* /usr/share/man/*'


COPY docker /docker
RUN  mv /docker/msmtprc /etc/msmtprc


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 5000

CMD exec docker/run
