
FROM debian:bookworm
MAINTAINER Dean Serenevy <dean@serenevy.net>

# CONFIGURATION
#--------------
VOLUME ["/opt/mariadb"]

# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV UID_MARIADB 201
ENV GID_MARIADB 201

INCLUDE ../_includes/05_localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
RUN groupadd --gid $GID_MARIADB mysql
RUN useradd --system     \
    -d /var/lib/mysql    \
    --shell /bin/false   \
    --no-create-home     \
    --uid $UID_MARIADB   \
    --gid $GID_MARIADB   \
    --comment mysql      \
    mysql

RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
    mariadb-server \
 && apt-get clean'

COPY docker /docker
RUN cd /docker \
 && ln -s mariadb mysql \
 && ln -s mariadb-admin mysqladmin \
 && ln -s mariadb-dump mysqldump \
 && echo '!includedir /opt/mariadb/etc/mariadb.conf.d/' >> /etc/mysql/mariadb.cnf


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker

# RUNNING
#--------
EXPOSE 3306

CMD exec docker/run
