#!/bin/bash
VERSION='0.1.0';# Created: 2016-02-13
set -o nounset     # Die if any variable is unset
set -o errexit     # set +e; COMMAND; set -e to temporarily disable

VOLUME=/www

ETC_DIR=$VOLUME/etc
LOG_DIR=$VOLUME/log

# ssmtp needs updated host name:
hname=`hostname`
[ -z "$hname"   ] || sed -i "/^#\\?hostname/chostname=$hname" /etc/ssmtp/ssmtp.conf
[ -z "$MAILHUB" ] || sed -i "/^#\\?mailhub/cmailhub=$MAILHUB" /etc/ssmtp/ssmtp.conf

# create directories
[ -d "$ETC_DIR" ] || install -d -o root -g root "$ETC_DIR"
[ -d "$LOG_DIR" ] || install -d -o root -g root "$LOG_DIR"
[ -d "$APACHE_RUN_DIR"  ] || install -d -o root -g root "$APACHE_RUN_DIR"
[ -d "$APACHE_LOCK_DIR" ] || install -d -o root -g root "$APACHE_LOCK_DIR"

# enable modules
for mod in $MODS_ENABLED; do
    a2enmod "$mod" >/dev/null
done

[ -f "$ETC_DIR/site.conf" ] || cat <<EOF > "$ETC_DIR/site.conf"
<VirtualHost *:80>
    ServerName  $hname
    ServerAlias www.$hname
    DocumentRoot $ROOT_DIR

    CustomLog $LOG_DIR/access.log combined
    ErrorLog  $LOG_DIR/error.log

    <Directory "$ROOT_DIR">
        AddHandler cgi-script .pl .cgi
        Options ExecCGI Includes FollowSymlinks
        AllowOverride None
        Require all granted
    </Directory>

    RedirectMatch 404 /\.git
    RedirectMatch 404 /\.svn
</VirtualHost>
EOF

exec /usr/sbin/apache2 -DFOREGROUND
