
FROM debian:stretch
MAINTAINER Dean Serenevy <dean@serenevy.net>

# CONFIGURATION
#--------------
VOLUME ["/opt/osticket"]

# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV APACHE_RUN_USER      www-data
ENV APACHE_RUN_GROUP     www-data
ENV APACHE_LOG_DIR       /var/log/apache2
ENV APACHE_PID_FILE      /var/run/apache2.pid
ENV APACHE_RUN_DIR       /var/run/apache2
ENV APACHE_LOCK_DIR      /var/lock/apache2
ENV APACHE_SERVERADMIN   someone@example.com
ENV APACHE_SERVERNAME    tickets
ENV APACHE_SERVERALIAS   tickets.example.com
ENV APACHE_DOCUMENTROOT  /var/www
ENV MAILHUB              127.0.0.1

INCLUDE ../_includes/05_localenv.docker

# Need to set env variables in this file:
INCLUDE? localenv.docker

INCLUDE ../_includes/10_setup.docker


# MAIN
#-----
RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
    apache2              \
    git                  \
    libapache2-mod-php   \
    php-apcu             \
    php-gd               \
    php-imap             \
    php-json             \
    php-mysql            \
    php-php-gettext      \
    ssmtp                \
 && apt-get clean'

RUN rm -f /etc/apache2/sites-enabled/000-default.conf
RUN ln -s /opt/osticket/etc/apache.conf /etc/apache2/sites-enabled/osticket.conf
RUN sed -i '/^;\?date\.timezone/cdate.timezone = "'$TIME_ZONE'"' /etc/php/7.0/apache2/php.ini
RUN sed -i '/^#\?FromLineOverride/cFromLineOverride=YES' /etc/ssmtp/ssmtp.conf

COPY docker /docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 80

CMD exec /docker/run
