
## This is a release builder, launch it, then once it is finished
## export/import the result to get a fixed object.

FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/osticket"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV APACHE_RUN_USER      www-data
ENV APACHE_RUN_GROUP     www-data
ENV APACHE_LOG_DIR       /var/log/apache2
ENV APACHE_PID_FILE      /var/run/apache2.pid
ENV APACHE_RUN_DIR       /var/run/apache2
ENV APACHE_LOCK_DIR      /var/lock/apache2
ENV APACHE_SERVERADMIN   dean@serenevy.net
ENV APACHE_SERVERNAME    tickets
ENV APACHE_SERVERALIAS   tickets.serenevy.net
ENV APACHE_DOCUMENTROOT  /var/www
ENV MAILHUB              172.17.42.1

INCLUDE ../_includes/05_localenv.docker
INCLUDE ../_includes/10_setup.docker


# MAIN
#-----
RUN apt-get update && apt-get install -y --no-install-recommends \
    apache2              \
    git                  \
    libapache2-mod-php5  \
    php-gettext          \
    php5-apcu            \
    php5-gd              \
    php5-imap            \
    php5-json            \
    php5-mysql           \
    ssmtp                \
 && apt-get clean

RUN rm -f /etc/apache2/sites-enabled/000-default.conf
RUN ln -s /opt/osticket/etc/apache.conf /etc/apache2/sites-enabled/osticket.conf
RUN sed -i '/^;\?date\.timezone/cdate.timezone = "'$TIME_ZONE'"' /etc/php5/apache2/php.ini
RUN sed -i '/^#\?FromLineOverride/cFromLineOverride=YES' /etc/ssmtp/ssmtp.conf

COPY docker /docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 80

CMD exec /docker/run
