
CONTAINER=puppet
REPOSITORY=cmminc/${CONTAINER}
TAG=deb11

LOCALENV=../_includes/05_localenv.docker

# make build     - Builds container for testing
# make commit    - Bump version and release
# make upgrade   - Upgrade packages (if needed), bumps revision, and release
# make release   - Builds and tags repository for "release"
include ../Makefile.common
