#!/usr/bin/perl -w
use strict; use warnings; use 5.014;

use Getopt::Long qw/:config bundling/;
use Hash::Util qw/ lock_keys /;
our $VERSION = '0.1.0';# Created: 2016-08-17

our %OPT = (  );
our @OPT_SPEC =
qw/ help|h version noact|no-act|dry-run DEBUG
  /;
sub USAGE { <<"__USAGE__" };
usage: $_[0] USERNAME
__USAGE__

use lib "/docker/lib";
use DockerSamba;
use IO::Prompt;

get_options( \%OPT, @OPT_SPEC );
MAIN(\%OPT, @ARGV);


sub MAIN {
    my ($opt, $uname) = @_;
    $uname = prompt("Username: ", '-t') unless $uname;
    usage("USERNAME required")    unless $uname;
    my $passwd = prompt("Password: ", -te => "*");
    usage("PASSWORD required")    unless $passwd;
    die "Passwords did not match, try again.\n" unless $passwd eq prompt("   Again: ", -te => "*");
    my $dsmb = DockerSamba->new;
    $dsmb->add_user($uname);
    $dsmb->set_passwd($uname, $passwd);
}

sub get_options {
    my $OPT = shift;
    GetOptions $OPT, @_ or usage(1);
    usage() if $$OPT{help} || $$OPT{version};
    lock_keys(%$OPT, keys %$OPT, map /^(\w+)/, @_);
}

sub usage {
    my $status = (@_ && $_[0] =~ /^\d+$/) ? shift(@_) : 0+@_;
    print @_, "\n" if @_;
    require File::Spec; my $exe = (File::Spec->splitpath($0))[2];
    $OPT{$_} = $OPT{$_} ? "enabled" : "disabled" for map /^(\w+).*!/, @OPT_SPEC;
    print $OPT{version} ? "$exe version $VERSION\n" : USAGE($exe);
    exit $status;
}
