#!/bin/bash
VERSION='0.1.0';# Created: 2015-05-20
set -o nounset     # Die if any variable is unset
set -o errexit     # set +e; COMMAND; set -e to temporarily disable

ETC_DIR=/opt/puppet/etc
install -d -o root   -g root   "$ETC_DIR"

PUPPET_MAJOR=$(puppet --version | awk -F. '{print$1}')
if [ "$PUPPET_MAJOR" != "8" ]; then
    echo "run script can only initialize settings for puppet 8"
    exit 1
fi

install -d -o root   -g root   "$ETC_DIR/default"
install -d -o puppet -g puppet /opt/puppet/lib /opt/puppet/log /opt/puppet/lib/yaml /opt/puppet/lib/yaml/facts

for f in $(find /etc/puppet.dpkg -type f | sed 's/^\/etc\/puppet\.dpkg\///'); do
    fdir="$(dirname "$f")"
    [ -e "$ETC_DIR/$fdir" ] || mkdir -p "$ETC_DIR/$fdir"
    [ -e "$ETC_DIR/$f" ]    || cp "/etc/puppet.dpkg/$f" "$ETC_DIR/$f"
done

# Generate CA if needed:
[ -d /etc/puppet/puppetserver/ca ] || puppetserver ca setup >/dev/null

echo "INITIALIZATION COMPLETE"
