#!/bin/bash
VERSION='0.1.0';# Created: 2015-05-20
set -o nounset     # Die if any variable is unset
set -o errexit     # set +e; COMMAND; set -e to temporarily disable

ETC_DIR=/opt/puppet/etc

# tmp and public needed for rack
install -d -o root   -g root   "$ETC_DIR" "$ETC_DIR/tmp" "$ETC_DIR/public"
install -d -o puppet -g puppet /opt/puppet/lib /opt/puppet/log

PUPPET_MAJOR=$(puppet --version | awk -F. '{print$1}')
check_version() {
    if [ "$PUPPET_MAJOR" != "5" ]; then
        echo "run script can only initialize settings for puppet 5"
        exit 1
    fi
}

if ! [ -f "$ETC_DIR/apache-passenger.conf" ]; then
    check_version
    cp /etc/apache2/sites-available/puppet-master.conf                                                            "$ETC_DIR/apache-passenger.conf"
    sed -i "s/\/usr\/share\/puppet\/rack\/puppet-master/\/opt\/puppet\/etc/"                                      "$ETC_DIR/apache-passenger.conf"
    sed -i 's/\/var\/lib\/puppet/\/opt\/puppet\/lib/'                                                             "$ETC_DIR/apache-passenger.conf"
    sed -i "/^\\s*SSLCertificateFile/c    SSLCertificateFile      /opt/puppet/lib/ssl/certs/$HOSTNAME.pem"        "$ETC_DIR/apache-passenger.conf"
    sed -i "/^\\s*SSLCertificateKeyFile/c SSLCertificateKeyFile   /opt/puppet/lib/ssl/private_keys/$HOSTNAME.pem" "$ETC_DIR/apache-passenger.conf"
fi

if ! [ -f "$ETC_DIR/config.ru" ]; then
    check_version
    cp /usr/share/puppet/rack/puppet-master/config.ru                                  "$ETC_DIR/config.ru"
    sed -i "/\"\-\-confdir\"/iARGV << \"--config\" << \"/opt/puppet/etc/puppet.conf\"" "$ETC_DIR/config.ru"
    sed -i "/\"\-\-confdir\"/cARGV << \"--confdir\" << \"/opt/puppet\""                "$ETC_DIR/config.ru"
    sed -i "/\"\-\-codedir\"/cARGV << \"--codedir\" << \"/opt/puppet/code\""           "$ETC_DIR/config.ru"
    sed -i "/\"\-\-vardir\"/cARGV << \"--vardir\" << \"/opt/puppet/lib\""              "$ETC_DIR/config.ru"
    sed -i "/\"\-\-logdir\"/cARGV << \"--logdir\" << \"/opt/puppet/log\""              "$ETC_DIR/config.ru"
fi

if ! [ -f "$ETC_DIR/puppet.conf" ]; then
    check_version
    cp /etc/puppet/puppet.conf.dpkg-dist                        "$ETC_DIR/puppet.conf"
    sed -i "s/=\s*\/var\/lib\/puppet/=\/opt\/puppet\/lib/"      "$ETC_DIR/puppet.conf"
    sed -i "s/=\s*\/var\/log\/puppet/=\/opt\/puppet\/log/"      "$ETC_DIR/puppet.conf"
    sed -i "/\[main\]/ahiera_config=/opt/puppet/etc/hiera.yaml" "$ETC_DIR/puppet.conf"
fi

chown puppet:puppet "$ETC_DIR/config.ru"

# Generate CA if needed:
puppet cert list -a >/dev/null

exec puppet master --verbose --no-daemonize --config /opt/puppet/etc/puppet.conf --confdir /opt/puppet --vardir /opt/puppet/lib
