
FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/opencart"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV APACHE_RUN_USER      www-data
ENV APACHE_RUN_GROUP     www-data
ENV APACHE_LOG_DIR       /var/log/apache2
ENV APACHE_PID_FILE      /var/run/apache2.pid
ENV APACHE_RUN_DIR       /var/run/apache2
ENV APACHE_LOCK_DIR      /var/lock/apache2
# ENV APACHE_SERVERADMIN   dean@serenevy.net
# ENV APACHE_SERVERNAME    store.routerbitclub.com
# ENV APACHE_SERVERALIAS   www.store.routerbitclub.com
ENV APACHE_DOCUMENTROOT  /var/www
# ENV MAILHUB              172.17.42.1

INCLUDE ../_includes/05_localenv.docker

INCLUDE localenv.docker

INCLUDE ../_includes/10_setup.docker

# MAIN
#-----

RUN apt-get update && apt-get install -y --no-install-recommends \
    apache2             \
    curl                \
    libapache2-mod-php5 \
    php5-curl           \
    php5-gd             \
    php5-mcrypt         \
    php5-mysql          \
    ssmtp               \
 && apt-get clean

RUN rm -f /etc/apache2/sites-enabled/000-default.conf
RUN ln -s /opt/opencart/etc/apache.conf /etc/apache2/sites-enabled/opencart.conf
RUN sed -i '/^;\?date\.timezone/cdate.timezone = "'$TIME_ZONE'"' /etc/php5/apache2/php.ini
RUN sed -i '/^#\?FromLineOverride/cFromLineOverride=YES' /etc/ssmtp/ssmtp.conf

RUN a2enmod rewrite

COPY docker /docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 80

CMD exec /docker/run
