
FROM debian:bookworm
MAINTAINER Dean Serenevy <dean@serenevy.net>
VOLUME ["/opt/puppet"]

# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV UID_PUPPET 200
ENV GID_PUPPET 200

INCLUDE ../_includes/05_localenv.docker
INCLUDE? localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
RUN groupadd --gid $GID_PUPPET puppet
RUN useradd --system     \
    -d /opt/puppet/lib   \
    --shell /bin/false   \
    --no-create-home     \
    --uid $UID_PUPPET    \
    --gid $GID_PUPPET    \
    --comment puppet     \
    puppet

RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
 puppetserver \
 puppet-module-puppetlabs-concat \
 puppet-module-puppetlabs-cron-core \
 puppet-module-puppetlabs-host-core \
 puppet-module-puppetlabs-inifile \
 puppet-module-puppetlabs-mount-core \
 puppet-module-puppetlabs-selinux-core \
 puppet-module-puppetlabs-sshkeys-core \
 puppet-module-puppetlabs-stdlib \
 puppet-module-puppetlabs-vcsrepo \
 && apt-get clean'

# Puppet defines its config path in a lot of places, rather then chase them
# all down, symlink /etc/puppet to /opt/puppet/etc
RUN mv -f /etc/puppet /etc/puppet.dpkg \
 && ln -s /opt/puppet/etc /etc/puppet \
 && mkdir /etc/puppet.dpkg/default \
 && cp /etc/default/puppetserver /etc/puppet.dpkg/default/ \
 && sed -i -e 's/\/var\/log\/puppetserver/\/opt\/puppet\/log/' \
    /etc/puppet.dpkg/puppetserver/conf.d/puppetserver.conf \
    /etc/puppet.dpkg/puppetserver/logback.xml \
    /etc/puppet.dpkg/puppetserver/request-logging.xml \
 && sed -i -e 's/\/var\/lib\/puppetserver/\/opt\/puppet\/lib/' \
    /etc/puppet.dpkg/puppetserver/conf.d/puppetserver.conf

COPY docker /docker

# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker

# RUNNING
#--------
EXPOSE 8140

CMD exec /docker/run
