
FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>

# jessie moved to archive.debian.org, containers not updated
RUN sed -i '/jessie-updates/d' /etc/apt/sources.list ; \
    sed -i 's/deb.debian.org/archive.debian.org/' /etc/apt/sources.list; \
    echo 'Acquire::Check-Valid-Until "false";' >/etc/apt/apt.conf.d/90_archive_expired_key; \
    echo 'APT::Get::AllowUnauthenticated "true";' >>/etc/apt/apt.conf.d/90_archive_expired_key


# CONFIGURATION
#--------------
VOLUME ["/www"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV APACHE_RUN_USER      www-data
ENV APACHE_RUN_GROUP     www-data
ENV APACHE_LOG_DIR       /www/log
ENV APACHE_PID_FILE      /var/run/apache2.pid
ENV APACHE_RUN_DIR       /var/run/apache2
ENV APACHE_LOCK_DIR      /var/lock/apache2

ENV MAILHUB              172.17.42.1
ENV ROOT_DIR             /www/root
ENV MODS_ENABLED=

INCLUDE ../_includes/05_localenv.docker

INCLUDE? localenv.docker

INCLUDE ../_includes/10_setup.docker


# MAIN
#-----
RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
    apache2                        \
    ssmtp                          \
 && apt-get clean'


# apache
RUN rm -f /etc/apache2/sites-enabled/000-default.conf /etc/apache2/conf-enabled/ledgersmb.conf
RUN ln -s /www/etc/site.conf /etc/apache2/sites-enabled/000-default.conf
RUN a2enmod cgid

# ssmtp
RUN sed -i '/^#\?FromLineOverride/cFromLineOverride=YES' /etc/ssmtp/ssmtp.conf

COPY docker /docker

INCLUDE? postinstall.docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 80

CMD exec /docker/run
