
FROM debian:stretch
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/git"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV UID_GIT 2002
ENV GID_GIT 2002
ENV SSH_SERVER_DIR /opt/git/ssh_server

INCLUDE ../_includes/05_localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
RUN addgroup --gid $GID_GIT git
RUN adduser                  \
    --home /opt/git          \
    --no-create-home         \
    --shell /bin/dash        \
    --uid $UID_GIT           \
    --gid $GID_GIT           \
    --gecos "Git Server,,,"  \
    --disabled-password      \
    --disabled-login         \
    git

RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
    gitolite3             \
    redis-tools           \
    ssh                   \
    sudo                  \
 && apt-get clean'

RUN mkdir /var/run/sshd

# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 22
WORKDIR /opt/git

CMD mkdir -p "$SSH_SERVER_DIR" ; [ -f "$SSH_SERVER_DIR/ssh_host_rsa_key.pub" ] || dpkg-reconfigure openssh-server ; /usr/sbin/sshd -D
