
## This is a release builder, launch it, then once it is finished
## export/import the result to get a fixed object.

FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/git"]


# BUILDING
#---------
INCLUDE docker/00_prepare.docker

ENV UID_GIT 2002
ENV GID_GIT 2002
ENV SSH_SERVER_DIR /opt/git/ssh_server

INCLUDE docker/05_localenv.docker
INCLUDE docker/10_setup.docker

# MAIN
#-----
RUN addgroup --gid $GID_GIT git
RUN adduser                  \
    --home /opt/git          \
    --no-create-home         \
    --shell /bin/dash        \
    --uid $UID_GIT           \
    --gid $GID_GIT           \
    --gecos "Git Server,,,"  \
    --disabled-password      \
    --disabled-login         \
    git

RUN apt-get update && apt-get install -y --no-install-recommends \
    gitolite3             \
    ssh                   \
    sudo

RUN mkdir /var/run/sshd

# CLEANUP
#--------
INCLUDE docker/99_cleanup.docker


# RUNNING
#--------
EXPOSE 22
WORKDIR /opt/git

CMD mkdir -p "$SSH_SERVER_DIR" ; [ -f "$SSH_SERVER_DIR/ssh_host_rsa_key.pub" ] || dpkg-reconfigure openssh-server ; /usr/sbin/sshd -D
