
# php7.3
FROM debian:buster
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/timeclock"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV APACHE_RUN_USER      www-data
ENV APACHE_RUN_GROUP     www-data
ENV APACHE_LOG_DIR       /opt/timeclock/log
ENV APACHE_PID_FILE      /var/run/apache2.pid
ENV APACHE_RUN_DIR       /var/run/apache2
ENV APACHE_LOCK_DIR      /var/lock/apache2

INCLUDE ../_includes/05_localenv.docker

INCLUDE? localenv.docker

INCLUDE ../_includes/10_setup.docker


# MAIN
#-----
# barcode, ghostscript, imagemagick for barcode rendering and conversion to png
RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
    apache2 \
    barcode \
    ghostscript \
    imagemagick \
    libapache2-mod-php \
    php-mysql \
    msmtp \
 && apt-get clean \
 && rm -rf /usr/share/doc/* /usr/share/man/man*/*'


RUN \
 rm -f /etc/apache2/sites-enabled/000-default.conf && \
 ln -s /opt/timeclock/etc/site.conf /etc/apache2/sites-enabled/timeclock.conf && \
 sed -i '/^;\?date\.timezone/cdate.timezone = "'$TIME_ZONE'"'   /etc/php/7.3/apache2/php.ini && \
 sed -i '/^;\?sendmail_path/csendmail_path = /usr/bin/msmtp -t' /etc/php/7.3/apache2/php.ini && \
 ln -s /opt/timeclock/etc/msmtprc /etc/msmtprc


COPY docker /docker

INCLUDE? postinstall.docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 80

CMD exec /docker/run
