
FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/opt/timeclock"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker
INCLUDE ../_includes/05_localenv.docker
INCLUDE ../_includes/10_setup.docker

# MAIN
#-----
RUN bash -c 'apt-get update && xargs -a <(awk "/^\\s*[^#]/" /tmp/apt.install) -- \
 apt-get install -y --no-install-recommends \
    apache2               \
    libapache2-mod-php5   \
    php5-mysql            \
 && apt-get clean'

RUN ln -s /opt/timeclock/etc/apache2/timeclock.conf /etc/apache2/sites-enabled/timeclock.conf

RUN a2enmod ssl

RUN rm -f /etc/apache2/sites-enabled/000-default.conf
RUN sed -i '/^session\.use_strict_mode/d'                        /etc/php5/apache2/php.ini
RUN sed -i '/^;\?date\.timezone/cdate.timezone = "'$TIME_ZONE'"' /etc/php5/apache2/php.ini

# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 80
EXPOSE 443

ENV APACHE_RUN_USER      www-data
ENV APACHE_RUN_GROUP     www-data
ENV APACHE_LOG_DIR       /var/log/apache2
ENV APACHE_PID_FILE      /var/run/apache2.pid
ENV APACHE_RUN_DIR       /var/run/apache2
ENV APACHE_LOCK_DIR      /var/lock/apache2
# ENV APACHE_SERVERADMIN   dean@serenevy.net
# ENV APACHE_SERVERNAME    timeclock
# ENV APACHE_SERVERALIAS   timeclock.machinemotion.com
ENV APACHE_DOCUMENTROOT  /var/www

# Need to set env variables (those which are commented above) in this file:
INCLUDE localenv.docker

CMD [ "/usr/sbin/apache2", "-DFOREGROUND" ]
