#!/bin/bash
VERSION='0.1.0';# Created: 2015-05-20
set -o nounset     # Die if any variable is unset
set -o errexit     # set +e; COMMAND; set -e to temporarily disable

ETC_DIR=/opt/osticket/etc
LOG_DIR=/opt/osticket/log
# DATA_DIR=/opt/osticket/data
SRC_DIR=/opt/osticket/src
WWW_DIR=/opt/osticket/www

# ssmtp needs updated host name:
hname=`hostname`
[ -z "$hname"   ] || sed -i "/^#\\?hostname/chostname=$hname" /etc/ssmtp/ssmtp.conf
[ -z "$MAILHUB" ] || sed -i "/^#\\?mailhub/cmailhub=$MAILHUB" /etc/ssmtp/ssmtp.conf

# apache configuration
[ -d "$ETC_DIR" ] || mkdir -p "$ETC_DIR"
[ -d "$LOG_DIR" ] || mkdir -p "$LOG_DIR"

[ -d "$SRC_DIR" ] || git clone https://github.com/osTicket/osTicket.git "$SRC_DIR"
[ -d "$WWW_DIR" ] || (
    pushd "$SRC_DIR"
    php setup/cli/manage.php deploy --setup "$WWW_DIR"
    popd
)

[ -f "$ETC_DIR/apache.conf" ] || cat <<EOF > "$ETC_DIR/apache.conf"
<VirtualHost *:80>
    ServerAdmin somebody@example.com
    ServerName ticket.example.com
    ServerAlias www.ticket.example.com

    CustomLog $LOG_DIR/access.log combined
    ErrorLog  $LOG_DIR/error.log

    DocumentRoot $WWW_DIR
    <Directory "$WWW_DIR">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    <Directory "$WWW_DIR/include">
        Require all denied
    </Directory>

    RedirectMatch 404 /\.git
    RedirectMatch 404 /\.svn
</VirtualHost>
EOF

exec /usr/sbin/apache2 -DFOREGROUND
