#!/bin/bash
VERSION='0.1.0';# Created: 2015-05-20
set -o nounset     # Die if any variable is unset
set -o errexit     # set +e; COMMAND; set -e to temporarily disable

ETC_DIR=/opt/puppet/etc

install -d -o root   -g root   "$ETC_DIR" "$ETC_DIR/tmp" "$ETC_DIR/public"
install -d -o puppet -g puppet /opt/puppet/lib /opt/puppet/log
chown puppet:puppet "$ETC_DIR/config.ru"

exec /usr/sbin/apache2 -DFOREGROUND
