#!/bin/sh

export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
export APACHE_LOG_DIR=/var/log/apache2
export APACHE_PID_FILE=/var/run/apache2.pid
export APACHE_RUN_DIR=/var/run/apache2
export APACHE_LOCK_DIR=/var/lock/apache2
export APACHE_SERVERADMIN=dean@serenevy.net
export APACHE_SERVERNAME=puppet
export APACHE_SERVERALIAS=puppet.machinemotion.com
export APACHE_DOCUMENTROOT=/var/www

exec /usr/sbin/apache2 -DFOREGROUND
