
FROM debian:jessie
MAINTAINER Dean Serenevy <dean@serenevy.net>


# CONFIGURATION
#--------------
VOLUME ["/www"]


# BUILDING
#---------
INCLUDE ../_includes/00_prepare.docker

ENV APACHE_RUN_USER      www-data
ENV APACHE_RUN_GROUP     www-data
ENV APACHE_LOG_DIR       /www/log
ENV APACHE_PID_FILE      /var/run/apache2.pid
ENV APACHE_RUN_DIR       /var/run/apache2
ENV APACHE_LOCK_DIR      /var/lock/apache2

ENV MAILHUB              172.17.42.1
ENV MODS_ENABLED=

INCLUDE ../_includes/05_localenv.docker

INCLUDE? localenv.docker

INCLUDE ../_includes/10_setup.docker


# MAIN
#-----
RUN apt-get update && apt-get install -y --no-install-recommends \
    apache2                        \
    ledgersmb                      \
    libimage-size-perl             \
    libmath-bigint-gmp-perl        \
    libopenoffice-oodoc-perl       \
    libparse-recdescent-perl       \
    libtemplate-plugin-latex-perl  \
    lmodern                        \
    perlmagick                     \
    ssmtp                          \
    texlive-latex-recommended      \
    texlive-pstricks               \
    texlive-xetex                  \
 && apt-get clean


# ledger
RUN cp -f /usr/share/doc/ledgersmb/examples/ledgersmb.conf.default /etc/ledgersmb/ledgersmb.conf.default
RUN sed -i '/^spool/cspool      = /www/spool' /etc/ledgersmb/ledgersmb.conf.default
RUN sed -i 's/ledgersmb\.conf/\/www\/etc\/ledgersmb.conf/' /usr/share/ledgersmb/LedgerSMB/Sysconfig.pm

# apache
RUN rm -f /etc/apache2/sites-enabled/000-default.conf /etc/apache2/conf-enabled/ledgersmb.conf
RUN ln -s /www/etc/site.conf /etc/apache2/sites-enabled/000-default.conf
RUN a2enmod cgid

# ssmtp
RUN sed -i '/^#\?FromLineOverride/cFromLineOverride=YES' /etc/ssmtp/ssmtp.conf

COPY docker /docker

INCLUDE? postinstall.docker


# CLEANUP
#--------
INCLUDE ../_includes/99_cleanup.docker


# RUNNING
#--------
EXPOSE 80

CMD exec /docker/run
